version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
  app:
    build:
      context: ./sample_app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
    volumes:
      - .:/app
      - tmp-data:/app/sample_app/tmp
      - public-data:/app/sample_app/public
    tty: true
  web:
    build:
      context: ./nginx
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 3000:80
    depends_on:
      - app
volumes:
  tmp-data:
  public-data: