version: '2'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
  web:
    build: .
    depends_on:
      - db
    environment:
      - PORT=3000
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    tty: true